config/routes.rb
Rails.application.routes.draw do
  resources :rubyists

  root 'rubyists#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rubyist.rb
class Rubyist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rubyists_controller.rb
class RubyistsController < ApplicationController

  def index
    rubyist = []
    client = Octokit::Client.new(:access_token => ENV["octokit_auth"])
    rubyists = client.search_users("location:Indianapolis language:Ruby", page: params[:page], sort: "joined", order: "asc")
    @indy_ruby = rubyists[:items].map{|x| Octokit.user(x.login)}
    @pages = (rubyists[:total_count] / 30.0).ceil
  end

  def show
    client = Octokit::Client.new(:access_token => ENV["octokit_auth"])
    @gits = client.list_repos("#{params[:id]}", page: params[:page], sort: "created_at", direction: "desc")
    rubyist = Octokit.user(params[:id])
    @pages = (rubyist[:public_repos] / 30.0).ceil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rubyists_helper.rb
module RubyistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IndyRubyists</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rubyists/index.html.erb
<div class="container">
  <h1 class="col-md-4 col-md-offset-4">Indy Rubyists</h1>
</div>
<br>
<div class="container">
  <ul class="list-inline col-md-4 col-md-offset-3">
    <% @pages.times do |x| %>
      <li><%= link_to "Page #{x + 1}", page: x + 1 %></li>
    <% end %>
  </ul>
</div>
<br>
<ul>
<% @indy_ruby.each do |rubyist| %>
  <ul class="list-inline row">
    <li class="col-md-2"><div class="col-md-5"><%= image_tag rubyist.avatar_url, class: "img-responsive" %></div></li>
    <li class="col-md-2">Indy Rubyist: <%= link_to rubyist[:login], rubyist.html_url %></li>
    <li class="col-md-2">Joined GitHub: <%= rubyist.created_at %></li>
    <li class="col-md-2 col-md-offset-1">Public Repos: <%= link_to rubyist.public_repos, rubyist_path(id: rubyist.login) %></li>
    <li class="col-md-2">Num of Followers: <%= rubyist.followers %></li>
  </ul>
  <hr>
<% end %>
</ul>
<br>
<div class="container">
  <ul class="list-inline col-md-4 col-md-offset-3">
    <% @pages.times do |x| %>
      <li><%= link_to "Page #{x + 1}", page: x + 1 %></li>
    <% end %>
  </ul>
</div>

app/views/rubyists/show.html.erb
<div class="container">
  <h1 class="col-md-6 text-align-center"><%= "#{params[:id]}" %> Repositories</h1>
  <h4 class="col-md-1 col-md-offset-4"><%= link_to "Home", root_path %></h4>
</div>
<br>
<ul class="list-inline col-md-offset-5">
  <% @pages.times do |x| %>
    <li><%= link_to "Page #{x + 1}", page: x + 1 %></li>
  <% end %>
</ul>
<br>
<ul>
  <% @gits.each do |git| %>
    <ul class="list-inline row">
      <li class="col-md-4 col-md-offset-1">Repository: <%= link_to git.name, git.html_url %></li>
      <li class="col-md-2">Created at: <%= git.created_at %></li>
      <li class="col-md-2 col-md-offset-1">Written in: <%= git.language %><li>
    </ul>
    <hr>
  <% end %>
</ul>
<br>
<ul class="list-inline col-md-offset-5">
  <% @pages.times do |x| %>
    <li><%= link_to "Page #{x + 1}", page: x + 1 %></li>
  <% end %>
</ul>